name: Java CI with gradle

on:
 push:
   branches: [ master ]

jobs:
	build:
		runs-on: ubuntu-latest

		steps:
		- uses: actions/checkout@v4 
  
    		- name: Set up JDK 21
      		  uses: actions/setup-java@v4
      		  with:
       			java-version: "21"
	   		distribution: "adopt"
      		- uses: actions/setup-java@v4
 		  with:
    			distribution: 'temurin'
    			java-version: '21'
    			cache: 'gradle'
    			cache-dependency-path: | # optional
      				sub-project/*.gradle*
      				sub-project/**/gradle-wrapper.properties
		- run: ./gradlew build --no-daemon
      		
